name: CI/CD Pipeline - Online Bookstore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
# Security scan runs first
# This is to catch security issues early before running tests or deployment
  security-scan:
    name: Security Scan (Bandit)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]
      
      - name: Run Bandit Security Scan
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . -f txt -o bandit-report.txt || true
          echo "================================"
          echo "  BANDIT SECURITY SCAN RESULTS"
          echo "================================"
          bandit -r . -ll -f txt
        continue-on-error: false
      
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-security-report
          path: |
            bandit-report.json
            bandit-report.txt
      
      - name: Bandit Summary
        if: always()
        run: |
          echo "## Security Scan Results (Bandit) " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Scan Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Tool:** Bandit (Python Security Linter)" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          bandit -r . -ll -f txt | head -50 >> $GITHUB_STEP_SUMMARY || true
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Download the full report from the workflow artifacts." >> $GITHUB_STEP_SUMMARY

# Runs unit tests first
# This is to catch basic functionality issues early before running more expensive integration tests
# Unit tests will only run if the security scan passes
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libzmq3-dev
         
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Unit Tests
        run: |
          python -m pytest test_app.py -v --tb=short --color=yes
      
      - name: Generate Unit Test Coverage Report
        run: |
          python -m pytest test_app.py --cov=app --cov=models --cov-report=xml --cov-report=term
      
      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: unit-test-coverage
          fail_ci_if_error: false
# Runs integration tests only if unit tests pass
# This is to ensure that we don't waste resources running integration tests if the basic functionality is broken
# the If: always() means that even if the job is cancelled we still get the summary of the scan
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run Integration Tests
        run: |
          python -m pytest test_integration.py -v --tb=short --color=yes
      
      - name: Generate Integration Test Coverage Report
        run: |
          python -m pytest test_integration.py --cov=app --cov=models --cov-report=xml --cov-report=term
      
      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: integrationtests
          name: integration-test-coverage
          fail_ci_if_error: false
# If all the previous steps pass
# we simulate a deployment
# No actual deployment takes place for 2 reasons:
# 1. This is a mock project and there is no real infrastructure to deploy to
# 2. I have no idea how to deploy python becasue its not Java 
  deploy:
    name: Mock Deployment
    runs-on: ubuntu-latest
    needs: [security-scan, unit-tests, integration-tests] 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Simulate Deploy to Test Environment
        run: |
          echo "================================"
          echo "  MOCK DEPLOYMENT TO STAGING"
          echo "================================"
          echo ""
          echo "Deployment Details:"
          echo "  • Branch: ${{ github.ref_name }}"
          echo "  • Commit: ${{ github.sha }}"
          echo "  • Author: ${{ github.actor }}"
          echo "  • Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo ""
          echo "Deployment Steps:"
          echo "  Code checkout complete"
          echo "  Dependencies installed"
          echo "  Pre-deployment checks passed"
          echo "  Deployment package created"
          echo "  Application deployed to staging"
          echo ""
          echo "Mock Staging URL: https://staging-bookstore-${GITHUB_SHA:0:7}.example.com"
          echo ""
          echo "================================"
          echo "  DEPLOYMENT SUCCESSFUL! "
          echo "================================"
      
      - name: Deployment summary
        run: |
          echo "## Deployment Summary " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** Staging (Mock)" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Author:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test Results" >> $GITHUB_STEP_SUMMARY
          echo "-  Unit Tests: Passed" >> $GITHUB_STEP_SUMMARY
          echo "-  Integration Tests: Passed" >> $GITHUB_STEP_SUMMARY
          echo "-  Smoke Tests: Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment URL" >> $GITHUB_STEP_SUMMARY
          echo " [Staging Environment](https://staging-bookstore-${GITHUB_SHA:0:7}.example.com)" >> $GITHUB_STEP_SUMMARY

 # This step will send a notification if the entire workflow succeeds or fails
 # It gives a nice identifier on the github repository page
 # and also emailed me every time it failed (which was annoying)
  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [security-scan, unit-tests, integration-tests, deploy]
    if: success()
    
    steps:
      - name: Success notification
        run: |
          echo "================================"
          echo "  CI/CD PIPELINE COMPLETED "
          echo "================================"
          echo ""
          echo "All stages completed successfully:"
          echo "  Security Scan (Bandit)"
          echo "  Unit Tests"
          echo "  Integration Tests"
          echo "  Mock Deployment"
          echo ""
          echo "Commit ${{ github.sha }} is ready for production!"
          echo "================================"

  notify-failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    needs: [security-scan, unit-tests, integration-tests, deploy]
    if: failure()
    
    steps:
      - name: Failure notification
        run: |
          echo "================================"
          echo "  CI/CD PIPELINE FAILED"
          echo "================================"
          echo ""
          echo "One or more stages failed."
          echo "Please review the workflow logs above."
          echo ""
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          echo "================================"